### ISSUE TITLE
All pixi V4 Spine examples are broken :V

### ISSUE THREAD

**Issue by SlawomirMazgaj** [pixijs/pixi-spine#105]
Hello again,
Looks like there's something wrong with all Spine animations [EXAMPLES](http://pixijs.github.io/examples/index.html?s=spine&f=pixie.js&title=Pixie&plugins=pixi-spine&v=dev) :( Not sure if spine plugin is simply out of date on example web page or it's something else.

**Comment by ivanpopelyshev** [comment]
Oh, yes, they are. I'll commit latest pixi-spine and pixi.js and it will solve that :)

**Comment by staff0rd** [comment]
Looks to be still an issue?

Also, I just took a look at integrating a spine myself (first time, noob to spine) and it doesn't seem to work right off the bat.  Notably [this](https://github.com/pixijs/pixi-spine/blob/master/bin/pixi-spine.js#L4256-L4259) fails due to `tintRgb` and `attachment.r/g/b` being null.

**Comment by ivanpopelyshev** [comment]
Its binary packages issue, I shout about it at every issue - we need a build farm. "pixi.js" file becomes outdated in both "pixi.js" and "examples" repository periodically. I updated the version at examples, but I dont have rights to upload it to main repository. You can use the one from my dropbox: https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds/pixi.js

**Comment by staff0rd** [comment]
Building both pixi.js and pixi-spine from source solved it, thanks.

**Comment by SlawomirMazgaj** [comment]
Looks like examples are working again :)
