### ISSUE TITLE
SpineLoaded forces you to use Spine generated atlas files

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi-spine#11]
Cross posting GoodBoyDigital/pixi.js#1280

**Comment by petterhyden** [comment]
We also have similar problems, as we run cache busting (md5 hash of file content) of all resources resulting in the atlas and json files not getting matching names. We need to be able to specify the atlas and json filenames separately.

**Comment by whizzkid** [comment]
I also would like the option to use textures not generated by spine. (TexturePacker for example) which gives nicer results. so we could just load the spineskeleton.json file, and load a separate texture (making sure it uses the same names)  

especially since i now have an atlasfile that Spine created that handles the alpha incorrectly. :\

**Comment by cursedcoder** [comment]
https://github.com/pixijs/pixi-spine/blob/master/examples/dynamic_texture_atlas.md
