### ISSUE TITLE
Some examples not working

### ISSUE THREAD

**Issue by suppayami** [pixijs/pixi-spine#191]
I have tried some of the official examples like the Vine and Goblins, they didn't work like intended. Maybe an implementation with `spine-runtime/spine-ts/webgl` is better?

**Comment by ivanpopelyshev** [comment]
This implementation is based on spine-ts, also it adds some pixi-specific features. There might be problems with some things because of my patches.

Are you sure that you use official examples for spine 3.5/3.6 and not something for 3.4?

Right now I dont have enough time to port all `spine-ts/webgl` examples here, and I need help with it. Just give me a zip-archive or make a fiddle that you think must work and it isnt, I'll look at it.

**Comment by ivanpopelyshev** [comment]
Sometimes when things worked differently in spine-ts and pixi-spine, we actually found bugs in spine-ts itself. I'm in contact with EsotericSoftware authors, so I can poke them if we find something like that again.

**Comment by suppayami** [comment]
Actually nevermind, I have tried again and it worked. Maybe I made some mistakes in the spine setup before.
I'm working on Spine integration for RPG Maker MV, I will contact again if there is any problem.

Thank you so much 😄

**Comment by ivanpopelyshev** [comment]
RMMV YEAH! 

No problem, you can contact me here, either in pixi slack. If you want to use slack, then i can send you invintation and there are some people who are working with RMMV too :) 

I believe you'll have questions about customization of loading process for it.

**Comment by suppayami** [comment]
Okay it would be nice. My email is public in my github profile :D

**Comment by ivanpopelyshev** [comment]
Done.
