### ISSUE TITLE
Loading with spineAtlasFile for multiple skeleton animations with one texture

### ISSUE THREAD

**Issue by markknol** [pixijs/pixi-spine#335]
I have an few animations that share the same texture. I exported with this setting
![image](https://user-images.githubusercontent.com/576184/74948033-ff19d080-53fb-11ea-85f3-4d3ff3b24e70.png)

Now I have this folder with animations:
![image](https://user-images.githubusercontent.com/576184/74944520-79dfed00-53f6-11ea-9154-8754f73e573e.png)

Now our project use a custom loader task that wrap around the pixi loader. Ideally I want to keep using this, instead of making a new routine (load atlas first, then jsons) just for this specific thing:

Our setup reads the directory, builds a file list based on that, which I just provide to the pixi loader. My idea was to make special case for this multispine assets, detect if there if a path has a json extension, then add path using `spineAtlasFile`) to the atlas in loader.add options.
```haxe
if (Path.extension(path) == "json" && path.contains("multispine")) {
  loader.add( path, untyped { metadata: { 
    spineAtlasFile: Path.directory(path) + "/multispine.atlas", 
  }});
}
```

Now this works already which is great, but there is one issue, the atlas file gets requested multiple times, which defeats the purpose (we want to combine things to load less)

![image](https://user-images.githubusercontent.com/576184/74948609-d3e3b100-53fc-11ea-99cb-b799939f31b0.png)

Is there any way to workaround this?

**Comment by ivanpopelyshev** [comment]
Solution is easy, however Im taking a break from pixi for a month, i cannot code it for you.

Please confirm that you looked in all examples  in "docs" , especially last one (reuse_texture)

**Comment by ivanpopelyshev** [comment]
If it doesnt work in your caae or there are more problems - go debug 'loader.ts' . Whole file is collection of experience of real projects. If you make new solution - please share it by making PR.

**Comment by markknol** [comment]
Thanks a lot, I missed that page in the documentation. It works as intended now. This is a great (hidden) feature :D

**Comment by markknol** [comment]
Actually, it doesnt work correctly. Yes, the warning is suppressed, but the file is still loaded multiple times: 
![image](https://user-images.githubusercontent.com/576184/74957643-21195000-5408-11ea-9695-a527c4e72742.png)

**Comment by ivanpopelyshev** [comment]
Of course! You can preload atlas and then load json files with another pixi loader. "Why cant i load it in the same?" "Why cant i crate temp object that is not loaded yet and pass it as atlas?" Blame our genius loader architecture.

Ok, so two solutions : 
1. Use ine loader for atlas, create it , pass existing atlas to loader that loads all spines
2. Add the same trick as in other pixi vanilla loaders (bitmaptext for example) , sorry cant link from mobile look in main pixi repo. Basically if there is resource with same name as you want atlas - take it. Pass atlas name in metadata check it inside spine loader

In both cases you HAVE to debug spine loader or even modify it. Thats how everyone else did it. We cannot provide universal solution to people because we are not a framework , and plugins are based on people experience. We can try make general solution when there will be enough data.

**Comment by ivanpopelyshev** [comment]
OK, proper answer for the issue:

We do not have main solution yet. However, there's a workaround:

Make one spine skeleton with all the textures , load it first. Use its atlas for other models.

```js
preLoader.add('mainSpine', 'img/main.json');

preLoader.load(() => {
  const options = {
      metadata: {
          spineAtlas: preLoader.resources.mainSpine.spineAtlas
      }
  };

  loader.add('hello', 'img/Cherry.json', options);
  loader.add('hello2', 'img/Bell.json', options);

  loader.load(onAssetsLoaded)
});

function onAssetsLoaded() {
//...
}
```

**Comment by ivanpopelyshev** [comment]
OK, I put it here:: https://github.com/pixijs/pixi-spine/blob/master/examples/single_atlas_multiple_models.md

**Comment by markknol** [comment]
Thanks for clarifying! 

Issue can be closed now.
