### ISSUE TITLE
Require.js error: PIXI is not defined

### ISSUE THREAD

**Issue by josimard** [pixijs/pixi-spine#88]
Hi, 
I am not sure how I we could use the pixi-spine plugin on a page that has require.js.
Somehow, when "require" is present, the global "PIXI" object is not available throwing this error:

> Uncaught ReferenceError: PIXI is not defined

I do not use require.js in project, but it is loaded before on the container... 

Here is the most simple setup to reproduce the issue:

```
<!DOCTYPE html>
<html lang="en">
<body>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.11/pixi.min.js"></script>
    <script type="text/javascript" src="js/pixi-spine.js"></script>
    <script>
        console.log(PIXI);
    </script>
</html>
```

Looking at [PIXI.js code](https://github.com/pixijs/pixi.js/blob/master/bin/pixi.js#L34), I am a bit confused where it sets the global PIXI reference or how to require the module...

**Comment by ivanpopelyshev** [comment]
I think pixi already has require.js inside, try to remove require.js lib from the list

**Comment by josimard** [comment]
Thanks Ivan, 
unfortunately I cannot remove it since my project is part of 3rd party container which uses require.js...

I found out that Browserify's [wrapper code](https://github.com/pixijs/pixi.js/blob/master/bin/pixi.js#L34) does check if 'define' exists and kicks in a different behavior. 

I successfully patched it this way by replacing:  
`define([],f)`

For:
`define("PIXI", [], f())`


I wonder if there could be a way to compile PIXI in a way to specify the module name and reference method like in my hack...

**Comment by englercj** [comment]
> I think pixi already has require.js inside

No, we do not ship with require.js built into the library. PIXI is always exported to global even in AMD/CommonJS environments:

https://github.com/pixijs/pixi.js/blob/master/src/index.js#L27-L28

Even with browserifies wrapper it should still export to global. I'm surprised it doesn't...

**Comment by roughearth** [comment]
I am having a very similar problem. When running in full AMD mode, most of the time Pixi and Pixi-spine work OK, but there is a race which Pixi usually wins. When built in to a single file, I *always* get the "PIXI is not defined" error. I've been able to use breakpoints to identify that the Pixi-spine factory function is running before Pixi's, even though they are being included in the correct order.

I have tried many different simple changes - too many to list here, but ranging from RequireJS shims to manually modifying the Browserify wrappers. None have worked, so I am about to try forking the repos and rebuild with RequireJS doing the packing rather than Browserify. I'd love it if I didn't have to, so I would really appreciate some help.

**Comment by englercj** [comment]
Why does pixi-spine run first, would be the first question I ask. Additionally, how are they packaged into a single file?

**Comment by roughearth** [comment]
HI @englercj, good questions...

> Why does pixi-spine run first?"

I'd love to know the answer to this, since it is the cause of my problem. Breakpoints on Browserify wrappers are reached in the correct order, but the PIXI-Spine factory function is run first (ie immediately).

> how are they packaged into a single file?

We're using RequireJS in Grunt via grunt-contrib-requirejs. Our app code is all written with "simplified CommonJS wrappers" as per the RequireJS spec.

Hope this helps

**Comment by josimard** [comment]
@englercj & @roughearth

> Why does pixi-spine run first?"

The AMD wrapper around PIXI does not refer a PIXI instance, but refers it's constructor. When a global define() exists, PIXI needs to be instantiated via a require() call first. pixi-spine run first because nothing has "required" PIXI.js yet. This is what my previous hack also changes.

Here is an [AMD wrapper that doesn't depend on require()](https://github.com/goldfire/howler.js/blob/master/howler.js#L1328) to exist.

> how are they packaged into a single file?

I had to package multiple libs into a single js file because our publisher's website restrictions.

I'm now thinking about using require.js since it's in memory, and/or there could be a process to ensure some AMD loaders are available from our build.

**Comment by englercj** [comment]
Hmm, good call on why it runs first. You can fix this by "requiring" PIXI in a stub so it exports before any other deps try to load it.

As far as a long-term fix, I'm honestly not sure what the best solution is, yet.

**Comment by josimard** [comment]
@englercj 
I think you are right about no best solution. I did not find a relevant option in the browserify compiler documentation, I lack experience with this one.

I found an interesting article where a developer exposes the bundle's require() method and allow getting a module instance: 
http://www.ryanbensonmedia.com/blog/exposing-a-module-in-browserify

Maybe plugins could make use of require() for increased compatibility.

**Comment by roughearth** [comment]
For reference, here is the workaround I have come up with. It's a little elliptical, but it works

HTML
```html
<script src="require.js"></script>
<script src="main.js"></script>
```
main.js
```javascript
require(["libs/pixi"], function() {
    require(["src/app"], function(game) {
        game.init();
    });
});
```

src/app.js
```javascript
define(function(require) {
	var PIXI = require("./pixiwrapper");

	// use PIXI Spine here
});
```

src/pixiwrapper.js
```javascript
define(function(require) {
    require("../libs/pixi-spine");

    return PIXI;
});
```
The key points are as follows

- Load a require `main.js` outside the Require eco system
- Explicitly load in PIXI here using the asynchronous version of `require()`
- Create a wrapper module for PIXI that does not list PIXI as a dependency, but does list PIXI Spine
- Do not shim PIXI Spine, just let it load. This is OK because `main.js` must have loaded PIXI before attempting to load `app.js`
- Exclude `main.js` from your build.
- This will cause the load order to be `main.js` -> `libx/pixi.js` -> everything else

**Comment by cursedcoder** [comment]
Can it be closed now? @josimard
